config/routes.rb
TwitterForFriends::Application.routes.draw do
  resources :videos

  resources :photos

  devise_for :friends

  devise_scope :friend do
    get '/friends/sign_out', :to => "devise/sessions#destroy"
  end

  resources :tweets do
    collection do
      get 'stream', :defaults => { :format => 'js' }
    end
  end

  resources :friends do
    collection do
      get 'online_status', :defaults => { :format => 'js' }
    end
  end

  root :to => 'high_voltage/pages#show', :id => 'home'

end

app/models/friend.rb
# == Schema Information
#
# Table name: friends
#
#  id                     :integer          not null, primary key
#  name                   :string
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  is_admin               :boolean
#  avatar                 :string
#

class Friend < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :name, :avatar
  has_many :tweets
  has_many :photos
  
  mount_uploader :avatar, AvatarUploader

  def admin?
  	is_admin? || "moira.hicks@gmail.com" == self.email || "darren.hicks@gmail.com" == self.email
  end
  
  def self.online_friends
    Friend.order("name").where('updated_at > ?', 12.seconds.ago)
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  before_filter :authenticate_friend!

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.order("updated_at desc")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friends }
    end
  end

  def online_status
    @friends = Friend.online_friends
    current_friend.updated_at = Time.now
    current_friend.save
     respond_to do |format|
       format.js { render :layout => false} # online_status.js.erb
     end
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
    @friend = Friend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friend }
    end
  end

  # GET /friends/new
  # GET /friends/new.json
  def new
    @friend = Friend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friend }
    end
  end

  # GET /friends/1/edit
  def edit
    @friend = Friend.find(params[:id])
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(params[:friend])
    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render json: @friend, status: :created, location: @friend }
      else
        format.html { render action: "new" }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friends/1
  # PUT /friends/1.json
  def update
    @friend = Friend.find(params[:id])

    respond_to do |format|
      if @friend.update_attributes(params[:friend])
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div data-id: '<%= friend.id %>'>
  <div class="avatar"><%= image_tag friend.avatar_url(:thumb) if friend.avatar_url %></div>
  <i class="icon-circle" style="color: #0f0;"></i>&nbsp;<b><%= friend.name %></b>
  <% last_tweet_time = (friend.tweets.order("created_at desc").limit(1).first.created_at) rescue nil %>
  <% if last_tweet_time %>
  	&nbsp;&nbsp;<div style="font-size: .8em; font-weight: normal;">last tweeted <%= time_ago_in_words(last_tweet_time) %> ago...</div>
  <% end %>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<h1>Listing friends </h1>

<table cellpadding="5" cellspacing="5">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Last Activity</th>
    <% if current_friend.admin? %>
    <th></th>
    <th></th>
    <th></th>
    <% end %>
  </tr>

<% @friends.each do |friend| %>
  <tr>
    <td><div class="avatar"><%= image_tag friend.avatar_url(:thumb) if friend.avatar_url %></div></td>
    <td><%= friend.name %></td>
    <td><%= time_ago_in_words(friend.updated_at) %> ago</td>
    <% if current_friend.admin? %>
    <td><%= link_to 'Show', friend %></td>
    <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
    <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if current_friend.admin? %>
<%= link_to 'Add New Friend', new_friend_path %>
<% end %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/online_status.js.erb
FriendsPoller.addFriends("<%= j render(@friends) %>");

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @friend.name %>
</p>


<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>