config/routes.rb
TwitterForFriends::Application.routes.draw do
  resources :videos

  resources :photos

  devise_for :friends

  devise_scope :friend do
    get '/friends/sign_out', :to => "devise/sessions#destroy"
  end

  resources :tweets do
    collection do
      get 'stream', :defaults => { :format => 'js' }
    end
  end

  resources :friends do
    collection do
      get 'online_status', :defaults => { :format => 'js' }
    end
  end

  root :to => 'high_voltage/pages#show', :id => 'home'

end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  message    :string
#  friend_id  :integer
#  created_at :datetime
#  updated_at :datetime
#  photo_id   :integer
#  video_id   :integer
#

class Tweet < ActiveRecord::Base
  belongs_to :friend

  belongs_to :photo
  belongs_to :video
  
  # attr_accessible :message, :friend_id, :photo_id

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_filter :authenticate_friend!

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order("created_at desc").page(params[:page]).per(45)
    @tweet = Tweet.new
    @friends = Friend.online_friends
    @photos = Photo.recent_photos
    @videos = Video.recent_videos
     respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
      format.js { render :layout => false} # index.js.erb
    end
  end

  def stream    
    @tweets = Tweet.order("created_at desc").where('id > ?', params[:after].to_i) if params[:after]
     respond_to do |format|
       format.js { render :layout => false} # stream.js.erb
     end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.message.blank?
      redirect_to tweets_url, :notice => "Please enter a message" 
      return
    end
    @tweet.friend = current_friend
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  private
    def tweet_params 
      params[:tweet].permit!
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="tweet_this">
    <%= f.text_field :message, style: "width:95%;", placeholder: "Compose message", autofocus: true, autocomplete: "off" %>
    <%= f.submit %>
    <div style="float:right;"><%= link_to "Upload Photo", new_photo_path %></div>
    <div style="float:right;"><%= link_to "Upload Video", new_video_path %> |&nbsp;</div>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div  data-id=<%= tweet.id %>>
    <div class="when"><%= time_ago_in_words( tweet.created_at ) %> ago</div>
    <div class="name"><%= tweet.friend.try(:name) %></div>
    <div class="avatar"><%= image_tag tweet.friend.avatar_url(:thumb) if tweet.friend.try(:avatar_url) %></div>
    <% if tweet.photo %>
      <%= render "tweet_photo", photo: tweet.photo %>
    <% elsif tweet.video %>
      <%= render "tweet_video", video: tweet.video %>
    <% else %>
      <div class="message"><%= tweet.message %></div>
    <% end %>
    <% if current_friend && current_friend.admin? %>
    <div class="admin">
      <%= link_to 'Show', tweet %>
      <%= link_to 'Edit', edit_tweet_path(tweet) %>
      <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <% end %>
</div>

app/views/tweets/_tweet_photo.html.erb
Uploaded a photo <b><%= photo.title %></b>
<%= link_to photo do %>
	    <span class="tweet-photo"><%= image_tag photo.image_url(:thumb) if photo.image_url %></span>
<% end %>

app/views/tweets/_tweet_video.html.erb
Uploaded a video <b><%= video.title %></b>
<%= link_to video do %>
	    <span class="tweet-photo"><%= image_tag video.image if video.image %></span>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class="span6">
	<h1>Tweets</h1>
	<% if current_friend && current_friend.admin? %>
	  <%= paginate @tweets %>
	<% end %>
	<%= render 'form' %>

	<%= content_tag :div, id: "tweets", data: {url: stream_tweets_url} do %>
	  <%= render @tweets %>
	<% end %>
	<br />
</div>

<div class="span6">
		<h1>Online Friends</h1>
		<div class="row-fluid">
			<%= content_tag :div, id: "friends", data: {url: online_status_friends_url} do %>
				<%= render @friends %>
			<% end %>
		</div>
		
	<h1>Recent Photos</h1>
	<div class="row-fluid">
		<% @photos.each do |photo| %>
		<div>
				<%= link_to photo do %>
					<div class="photo-recent span3">
						<%= image_tag(photo.image_url(:thumb), alt: photo.title, class: "photo-thumb") if photo.image_url %>
						<div class="avatar">
							<%= image_tag photo.friend.avatar_url(:thumb) if photo.friend.avatar_url %>
						</div>
					</div>
				<% end %>
		</div>
		<% end %>
	</div>

	<h1>Recent Videos</h1>
	<div class="row-fluid">
		<%= @videos.each do |video| %>
		<div>
				<%= link_to video do %>
					<div class="photo-recent span3">
						<%= image_tag(video.image, alt: video.title, class: "photo-thumb") if video.image %>
						<div class="avatar">
							<%= image_tag video.friend.avatar_url(:thumb) if video.friend.avatar_url %>
						</div>
					</div>
				<% end %>
		</div>
		<% end %>
	</div>

</div>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @tweet.message %>
</p>

<p>
  <b>Friend:</b>
  <%= @tweet.friend.name %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/stream.js.erb
TweetsPoller.addTweets("<%= j render(@tweets) %>");