config/routes.rb
TwitterForFriends::Application.routes.draw do
  resources :videos

  resources :photos

  devise_for :friends

  devise_scope :friend do
    get '/friends/sign_out', :to => "devise/sessions#destroy"
  end

  resources :tweets do
    collection do
      get 'stream', :defaults => { :format => 'js' }
    end
  end

  resources :friends do
    collection do
      get 'online_status', :defaults => { :format => 'js' }
    end
  end

  root :to => 'high_voltage/pages#show', :id => 'home'

end

app/views/layouts/_navigation.html.haml
%nav{class:"navbar navbar-default navbar-fixed-top",role:"navigation"}
  .container-fluid
    .navbar-header
      %button{type:"button",class:"navbar-toggle",data:{toggle:"collapse",target:"#nav-menu"}}
        %span{class:"sr-only"} Toggle navigation
        %span{class:"icon-bar"}
        %span{class:"icon-bar"}
        %span{class:"icon-bar"}
      %a{class:"navbar-brand",href:"/"} Twitter For Friends
    #nav-menu{class:"collapse navbar-collapse"}
      %ul{class:"nav navbar-nav"}
        %li=link_to "Friends", friends_path
        %li=link_to "Tweets", tweets_path
        %li=link_to "Photos", photos_path
        %li=link_to "Videos", videos_path
        -if current_friend
          %li{class:"dropdown"}  
            %a{href:"#", class:"dropdown-toggle", "data-toggle" => "dropdown"}
              =current_friend.email  
            %ul{class:"dropdown-menu"}
              %li
                =link_to "Account", edit_friend_registration_path
                =link_to "Logout", destroy_friend_session_path, method: :delete
        -else
          %li=link_to "Login", new_friend_session_path
          %li=link_to "Sign Up", new_friend_registration_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter For Friends</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<embed src="/assets/messageReceived.wav" autostart="false" width="0" height="0" id="messageReceivedSound" enablejavascript="true">
<script>
function EvalSound(soundobj) {
  var thissound=document.getElementById(soundobj);
  thissound.Play();
}
</script>

<%= render 'layouts/navigation' %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="offset1 span10">
			<%= yield %>
		</div>
	</div>
</div>
</body>
</html>